#!/bin/bash

set -x

# if there is no args passed, try to check if there is any dogecoin.conf
if [ $# -eq 0 ]; then
	if [ ! -e "$HOME/.litecoin/litecoin.conf" ]; then
		mkdir -p $HOME/.litecoin

		echo "Creating litecoin.conf"

		# Seed a random password for JSON RPC server
		cat <<EOF > $HOME/.litecoin/litecoin.conf
disablewallet=1
printtoconsole=1
rpcuser=${RPCUSER:-litecoinrpc}
rpcpassword=${RPCPASSWORD:-`dd if=/dev/urandom bs=33 count=1 2>/dev/null | base64`}
EOF

	fi

	cat $HOME/.litecoin/litecoin.conf
fi

exec litecoind "$@"
